/**
 * @author Tim
 * @overview generated by ghoti-cli
 * @fileoverview Component set ComponentGhotiLeftBar
 */

import * as React from 'react';
import * as Func from '../func/import';
import * as Lambda from '../lambda/import';

import Config from '../config/config';
import logo from '../func/logo'

export interface IProps {
    page: String
    pushPage: any
}

export interface IState {

}

class ComponentGhotiLeftBar extends React.Component<IProps, IState> {
    public constructor(props) {
        super(props);

    }

    public render() {
        if (localStorage.getItem("Authority") === '5') {
            if (this.props.page === "main" || "register" || "userProfile" || "generalProfile") {
                return (
                    <div className="wrapper">
                        <div className="sidebar">
                            <div className="sidebar-header">
                                <button style={{
                                    width: "100%",
                                    backgroundColor: "Transparent",
                                    border: "none",
                                }}>
                                    <div className="logo">
                                        <img style={{
                                            width: "100%"
                                        }} src={logo} />
                                    </div>
                                    <div className="rpnname">
                                        RPN Company
                                    </div>
                                </button>
                            </div>
                            <div className="sidebar-body">

                                <div style={{
                                    borderBottom: "1px solid #E5E5E5"
                                }} className="sidebar-body-action">
                                    <div style={{ paddingTop: "5%" }}>
                                        <button className="link" style={{
                                            width: "100%",
                                            backgroundColor: "Transparent",
                                            border: "none",
                                            outline: "none"
                                        }} onClick={this.props.pushPage.bind(this, "/main")}>
                                            <div className="body-icon"><i style={{ color: "#616161" }} className="fas fa-tasks"></i></div>
                                            <div className="body-text">Dashboard</div>
                                        </button>
                                    </div>
                                </div>
                                <div className="sidebar-body-action">
                                    <div style={{ paddingTop: "5%" }}>
                                        <button className="link" style={{
                                            width: "100%",
                                            backgroundColor: "Transparent",
                                            border: "none",
                                            outline: "none"
                                        }} onClick={this.props.pushPage.bind(this, "/addtask")}>
                                            <div className="body-icon"><i style={{ color: "#FF882C" }} className="fas fa-plus"></i></div>
                                            <div className="body-text">Add Task</div>
                                        </button>
                                    </div>
                                </div>
                                <div style={{

                                }} className="sidebar-body-action">
                                    <div style={{ paddingTop: "5%" }}>
                                        <button className="link" style={{
                                            width: "100%",
                                            backgroundColor: "Transparent",
                                            border: "none",
                                            outline: "none"
                                        }} onClick={this.props.pushPage.bind(this, "/register")}>
                                            <div className="body-icon"><i style={{ color: "#AFA35F" }} className="fas fa-user-plus"></i></div>
                                            <div className="body-text">Register</div>
                                        </button>
                                    </div>
                                </div>
                                <div style={{
                                    borderBottom: "1px solid #E5E5E5"
                                }} className="sidebar-body-action">
                                    <div style={{ paddingTop: "5%" }}>
                                        <button className="link" style={{
                                            width: "100%",
                                            backgroundColor: "Transparent",
                                            border: "none",
                                            outline: "none"
                                        }} onClick={this.props.pushPage.bind(this, "/generalProfile")}>
                                            <div className="body-icon"><i style={{ color: "#4B47FF" }} className="fas fa-address-card"></i></div>
                                            <div className="body-text">Profile</div>
                                        </button>
                                    </div>
                                </div>
                                <div style={{

                                }} className="sidebar-body-action">
                                    <div style={{ paddingTop: "5%" }}>
                                        <button className="link" style={{
                                            width: "100%",
                                            backgroundColor: "Transparent",
                                            border: "none",
                                            outline: "none"
                                        }} onClick={this.props.pushPage.bind(this, "/develop")}>
                                            <div className="body-icon"><i style={{ color: "#AFA35F" }} className="fab fa-alipay"></i></div>
                                            <div className="body-text">Develop</div>
                                        </button>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>

                )
            }
            else {
                return (
                    <div>error</div>
                )
            }
        }
        else if (localStorage.getItem("Authority") === '3' || localStorage.getItem("Authority") === '4') {
            return (
                <div className="wrapper">
                    <div className="sidebar">
                        <div className="sidebar-header">
                            <button style={{
                                width: "100%",
                                backgroundColor: "Transparent",
                                border: "none",
                            }}>
                                <div className="logo">
                                    <img style={{
                                        width: "100%"
                                    }} src={logo} />
                                </div>
                                <div className="rpnname">
                                    RPN Company
                                </div>
                            </button>
                        </div>
                        <div className="sidebar-body">

                            <div style={{
                                borderBottom: "1px solid #E5E5E5"
                            }} className="sidebar-body-action">
                                <div style={{ paddingTop: "5%" }}>
                                    <button className="link" style={{
                                        width: "100%",
                                        backgroundColor: "Transparent",
                                        border: "none",
                                        outline: "none"
                                    }} onClick={this.props.pushPage.bind(this, "/main")}>
                                        <div className="body-icon"><i style={{ color: "#616161" }} className="fas fa-tasks"></i></div>
                                        <div className="body-text">Dashboard</div>
                                    </button>
                                </div>
                            </div>
                            <div className="sidebar-body-action">
                                <div style={{ paddingTop: "5%" }}>
                                    <button className="link" style={{
                                        width: "100%",
                                        backgroundColor: "Transparent",
                                        border: "none",
                                        outline: "none"
                                    }} onClick={this.props.pushPage.bind(this, "/addtask")}>
                                        <div className="body-icon"><i style={{ color: "#FF882C" }} className="fas fa-plus"></i></div>
                                        <div className="body-text">Add Task</div>
                                    </button>
                                </div>
                            </div>
                            <div style={{

                            }} className="sidebar-body-action">
                                <div style={{ paddingTop: "5%" }}>
                                    <button className="link" style={{
                                        width: "100%",
                                        backgroundColor: "Transparent",
                                        border: "none",
                                        outline: "none"
                                    }} onClick={this.props.pushPage.bind(this, "/register")}>
                                        <div className="body-icon"><i style={{ color: "#AFA35F" }} className="fas fa-user-plus"></i></div>
                                        <div className="body-text">Register</div>
                                    </button>
                                </div>
                            </div>

                        </div>
                    </div>
                </div>
            )
        }
        else {
            return (
                <div className="wrapper">
                    <div className="sidebar">
                        <div className="sidebar-header">
                            <button style={{
                                width: "100%",
                                backgroundColor: "Transparent",
                                border: "none",
                            }}>
                                <div className="logo">
                                    <img style={{
                                        width: "100%"
                                    }} src={logo} />
                                </div>
                                <div className="rpnname">
                                    RPN Company
                                </div>
                            </button>
                        </div>
                        <div className="sidebar-body">

                            <div style={{
                                borderBottom: "1px solid #E5E5E5"
                            }} className="sidebar-body-action">
                                <div style={{ paddingTop: "5%" }}>
                                    <button className="link" style={{
                                        width: "100%",
                                        backgroundColor: "Transparent",
                                        border: "none",
                                        outline: "none"
                                    }} onClick={this.props.pushPage.bind(this, "/main")}>
                                        <div className="body-icon"><i style={{ color: "#616161" }} className="fas fa-tasks"></i></div>
                                        <div className="body-text">Dashboard</div>
                                    </button>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            )
        }
    }
}

export default ComponentGhotiLeftBar;
