/**
 * @author Tim
 * @overview generated by ghoti-cli
 * @fileoverview Component set ComponentGhotiListGroupCollapse
 */

import * as React from 'react';
import * as Func from '../func/import';
import * as Lambda from '../lambda/import';

import Config from '../config/config';
import { ListGroupItem, Collapse } from 'reactstrap';

export interface IProps {
    Username: any;
}

export interface IState {

}

class ComponentGhotiListGroupCollapse extends React.Component<IProps, IState> {
    state = {
        collapse: false
    }
    public constructor(props) {
        super(props);
    }

    public render() {
        return (<React.Fragment>
            {/* <ListGroupItem> */}
                
                    <button className="btn btn-link btn-sm" style={{fontSize:"13px"}}onClick={() => { this.setState({ collapse: !this.state.collapse }) }}>ShowUser</button>
                    <Collapse isOpen={this.state.collapse}>{this.showUser(this.props.Username)}</Collapse>
                
            {/* </ListGroupItem> */}
        </React.Fragment>);
    }

    protected showUser(username) {
        if (username === null) {
            return <div>none</div>
        }
        if (username.length == 1) {
            return (
                <React.Fragment>
                    <li>Initial: {username[0]}</li>
                    <li>Bid: {void 0}</li>
                    <li>WorkOrder: {void 0}</li>
                    <li>Invoice: {void 0}</li>
                    <li>Pending Account Review: {void 0}</li>
                    <li>Complete: {void 0}</li>
                    <li>Archived: {void 0}</li>
                </React.Fragment>
            )
        }
        else if (username.length == 2) {
            return (
                <React.Fragment>
                    <li>Initial: {username[0]}</li>
                    <li>Bid: {username[1]}</li>
                    <li>WorkOrder: {void 0}</li>
                    <li>Invoice: {void 0}</li>
                    <li>Pending Account Review: {void 0}</li>
                    <li>Complete: {void 0}</li>
                    <li>Archived: {void 0}</li>
                </React.Fragment>
            )
        }
        else if (username.length == 3) {
            return (
                <React.Fragment>
                    <li>Initial: {username[0]}</li>
                    <li>Bid: {username[1]}</li>
                    <li>WorkOrder: {username[2]}</li>
                    <li>Invoice: {void 0}</li>
                    <li>Pending Account Review: {void 0}</li>
                    <li>Complete: {void 0}</li>
                    <li>Archived: {void 0}</li>
                </React.Fragment>
            )
        }
        else if (username.length == 4) {
            return (
                <React.Fragment>
                    <li>Initial: {username[0]}</li>
                    <li>Bid: {username[1]}</li>
                    <li>WorkOrder: {username[2]}</li>
                    <li>Invoice: {username[3]}</li>
                    <li>Pending Account Review: {void 0}</li>
                    <li>Complete: {void 0}</li>
                    <li>Archived: {void 0}</li>
                </React.Fragment>
            )
        }
        else if (username.length == 5) {
            return (
                <React.Fragment>
                    <li>Initial: {username[0]}</li>
                    <li>Bid: {username[1]}</li>
                    <li>WorkOrder: {username[2]}</li>
                    <li>Invoice: {username[3]}</li>
                    <li>Pending Account Review: {username[4]}</li>
                    <li>Complete: {void 0}</li>
                    <li>Archived: {void 0}</li>
                </React.Fragment>
            )
        }
        else if (username.length == 6) {
            return (
                <React.Fragment>
                    <li>Initial: {username[0]}</li>
                    <li>Bid: {username[1]}</li>
                    <li>WorkOrder: {username[2]}</li>
                    <li>Invoice: {username[3]}</li>
                    <li>Pending Account Review: {username[4]}</li>
                    <li>Complete: {username[5]}</li>
                    <li>Archived: {void 0}</li>
                </React.Fragment>
            )
        }
        else {
            <React.Fragment>
                <li>Initial: {username[0]}</li>
                <li>Bid: {username[1]}</li>
                <li>WorkOrder: {username[2]}</li>
                <li>Invoice: {username[3]}</li>
                <li>Pending Account Review: {username[4]}</li>
                <li>Complete: {username[5]}</li>
                <li>Archived: {username[6]}</li>
            </React.Fragment>
        }
    }
}

export default ComponentGhotiListGroupCollapse;
