/**
 * @author Tim
 * @overview generated by ghoti-cli
 * @fileoverview Component set ComponentGhotiTopBar
 */

import * as React from 'react';
import * as Func from '../func/import';
import * as Lambda from '../lambda/import';
import logo from '../func/logo'

import Config from '../config/config';

export interface IProps {
    page: String
    pushPage: any
}

export interface IState {

}

class ComponentGhotiTopBar extends React.Component<IProps, IState> {
    public constructor(props) {
        super(props);
    }

    public render() {
        return (
            <div className="topBar">
                <div className="searchBox">
                    <div className="input-group"
                        style={{
                            width: "50%",
                            paddingTop: "20px",
                            marginLeft: "40px",
                            // border:"1px solid black"
                        }}>
                        {/* <input type="text" className="form-control bg-light border-0 small" placeholder="Search for Addr..." aria-label="Search" aria-describedby="basic-addon2"></input>
                        <div className="input-group-append">
                            <button className="btn btn-primary" type="button">
                                <i className="fas fa-search fa-sm"></i>
                            </button>
                        </div> */}
                    </div>
                </div>
                <div className="profileBox">
                    <div style={{
                        paddingTop:"5%",
                        float: "right"
                    }}>
                        <button className="link" style={{
                            // width: "180px",
                            float: "right",
                            backgroundColor: "Transparent",
                            border: "none",
                            outline: "none"
                        }}onClick={this.props.pushPage.bind(this,"/userProfile")}>
                            <span style={{
                                color:"#616161",
                                float: "right"
                            }} className="mr-2 d-none d-lg-inline text-gray-600">{localStorage.getItem("currUser")}</span>
                            {/* <img style={{
                                width: "20%"
                            }} className="img-profile rounded-circle" src={logo} /> */}
                        </button>
                    </div>

                </div>
            </div>
        )
    }
}

export default ComponentGhotiTopBar;
