/**
 * @author Tim
 * @overview generated by ghoti-cli
 * @fileoverview Page set PageGhotiAddtask
 */

import * as React from 'react';
import * as Component from '../component/import';
import * as Func from '../func/import';
import * as Lambda from '../lambda/import';

import Config from '../config/config';

import * as $ from "jquery";

export interface IProps {
    history: any
}

export interface IState {

}



class PageGhotiAddtask extends React.Component<IProps, IState> {

    state = {
        alluser: [],
        username: "",
        clients: [],
        company: "",
    };

    public constructor(props) {
        super(props);
        this.pushPage = this.pushPage.bind(this);
    }

    public componentDidMount() {
        $.ajax({
            url: 'https://rpnserver.appspot.com/findAllUsers',

            headers: {
                Authorization: "Bearer " + localStorage.getItem('Token'),
            },
            method: 'GET',
            datatype: "json",
            data: JSON.stringify({
            }),
            success: (function (result) {
                console.log(result);
                this.setState({ alluser: result });
            }).bind(this),
        });
        $.ajax({
            url: 'https://rpnserver.appspot.com/findAllClient',

            headers: {
                Authorization: "Bearer " + localStorage.getItem('Token'),
            },
            method: 'GET',
            datatype: "json",
            data: JSON.stringify({
            }),
            success: (function (result) {
                console.log(result);
                this.setState({ clients: result });
            }).bind(this),
        });
    }

    public render() {
        return (<div className="page">
            <Component.leftBar page="register" pushPage={this.pushPage.bind(this)} />
            <Component.topBar page="register" pushPage={this.pushPage.bind(this)} />
            <div className="content" style={{ display: "fixed" }}>
                <div style={{
                    color: "#283747",
                    fontWeight: "bold",
                    fontSize: "22px",
                    marginLeft: "15px",
                    marginTop: "5px"
                }}>Add Task</div>
                <div className="mainTable">
                    <div className="card shadow mb-4">
                        <div className="card-header py-3">
                    
                        </div>
                        <div className="card-body py-3">
                    
                        </div>
                        
                    </div>
                </div>
            </div>
        </div>);
    }

    protected pushPage(page: String) {
        this.props.history.push(page)
    }
}

export default PageGhotiAddtask;
