/**
 * @author Tim
 * @overview generated by ghoti-cli
 * @fileoverview Page set PageGhotiAddtask
 */

import * as React from 'react';
import * as Component from '../component/import';
import * as Func from '../func/import';
import * as Lambda from '../lambda/import';

import Config from '../config/config';

import * as $ from "jquery";

export interface IProps {
    history: any
}

export interface IState {

}



class PageGhotiAddtask extends React.Component<IProps, IState> {
    height: number = 0
    state = {
        alluser: [],
        allVendors:[],
        username: "",
        clients: [],
        client: "",
        vendor:"",
    };

    public constructor(props) {
        super(props);
        this.pushPage = this.pushPage.bind(this);
        this.submitTask = this.submitTask.bind(this);
    }

    public componentDidMount() {
        $.ajax({
            url: 'https://rpntechserver.appspot.com/findAllClient',

            headers: {
                Authorization: "Bearer " + localStorage.getItem('Token'),
            },
            method: 'GET',
            datatype: "json",
            data: JSON.stringify({
            }),
            success: (function (result) {
                console.log(result);
                this.setState({ clients: result });
            }).bind(this),
        });
        $.ajax({
            url: 'https://rpntechserver.appspot.com/findAllVendors',

            headers: {
                Authorization: "Bearer " + localStorage.getItem('Token'),
            },
            method: 'GET',
            datatype: "json",
            data: JSON.stringify({
            }),
            success: (function (result) {
                console.log(result);
                this.setState({ allVendors: result });
            }).bind(this),
        });
    }

    public render() {
        this.height = window.innerHeight * 0.75
        return (<div className="page">
            <Component.leftBar page="register" pushPage={this.pushPage.bind(this)} />
            <Component.topBar page="register" pushPage={this.pushPage.bind(this)} />
            <div className="content" style={{ display: "fixed" }}>
                <div style={{
                    color: "#283747",
                    fontWeight: "bold",
                    fontSize: "22px",
                    marginLeft: "15px",
                    marginTop: "5px"
                }}>Add Task</div>
                <div className="mainTable">
                    <div className="card shadow mb-4">
                        <div className="card-header py-3">

                        </div>
                        <div style={{height: this.height, overflow: "auto"}}className="card-body py-3">
                            <div className="panel panel-info">
                                <form className="form-horizontal" method="post">
                                    <div id="div_id_propertyaddress" className="form-group required">
                                        <label className="control-label col-md-4  requiredField"> Property Address<span className="asteriskField"></span> </label>
                                        <div className="controls col-md-8 ">
                                            <input className="input-md  textinput textInput form-control" id="propaddr" name="propaddr" placeholder="Property Address" style={{ marginBottom: "5px" }} type="text" ></input>
                                        </div>
                                    </div>
                                    <div id="div_id_assetnumber" className="form-group required">
                                        <label className="control-label col-md-4  requiredField"> Asset Number<span className="asteriskField"></span> </label>
                                        <div className="controls col-md-8 ">
                                            <input className="input-md  textinput textInput form-control" id="assetnum" name="assetnum" placeholder="Asset Number" style={{ marginBottom: "5px" }} type="text" ></input>
                                        </div>
                                    </div>
                                    <div id="div_id_startdate" className="form-group required">
                                        <label className="control-label col-md-4  requiredField"> Start Date<span className="asteriskField"></span> </label>
                                        <div className="controls col-md-8 ">
                                            <input className="input-md  textinput textInput form-control" id="startdate" name="startdate" placeholder="Start Date" style={{ marginBottom: "5px" }} type="date" ></input>
                                        </div>
                                    </div>
                                    <div id="div_id_duedate" className="form-group required">
                                        <label className="control-label col-md-4  requiredField"> Due Date<span className="asteriskField"></span> </label>
                                        <div className="controls col-md-8 ">
                                            <input className="input-md  textinput textInput form-control" id="duedate" name="duedate" placeholder="Due Date" style={{ marginBottom: "5px" }} type="date" ></input>
                                        </div>
                                    </div>
                                    <div className="form-row" style={{marginLeft:"10px"}}>
                                        <div className="form-group col-md-2">
                                            <label >State</label>
                                            <input type="text" className="form-control" id="state" />
                                        </div>
                                        <div className="form-group col-md-2">
                                            <label>County</label>
                                            <input type="text" className="form-control" id="county" />
                                        </div>
                                        <div className="form-group col-md-2">
                                            <label>City</label>
                                            <input type="text" className="form-control" id="city" />
                                        </div>
                                        <div className="form-group col-md-2">
                                            <label>ZipCode</label>
                                            <input type="text" className="form-control" id="zipcode" />
                                        </div>
                                    </div>

                                    <div id="div_id_desc" className="form-group required">
                                        <label className="control-label col-md-4  requiredField"> Description<span className="asteriskField"></span> </label>
                                        <div className="controls col-md-8 ">
                                            <textarea className="input-md  textinput textInput form-control" id="description" name="description" placeholder="Desscription" style={{ marginBottom: "5px" }}></textarea>
                                        </div>
                                    </div>
                                    <div id="div_id_LBnum" className="form-group required">
                                        <label className="control-label col-md-4  requiredField">Lock Box Number<span className="asteriskField"></span> </label>
                                        <div className="controls col-md-8 ">
                                            <input className="input-md  textinput textInput form-control" id="lockboxnumber" name="lockboxnumber" placeholder="Lock Box Number" style={{ marginBottom: "5px" }} type="text" ></input>
                                        </div>
                                    </div>
                                    <div className="form-row" style={{marginLeft:"10px"}}>
                                        <div className="form-group col-md-2">
                                            <label>Client</label>
                                            <select className="form-control" id='client' onChange={e => { this.setState({ client: e.target.value }) }}>
                                                <option>Choose Client</option>
                                                {this.state.clients ? this.state.clients.map(function (item, key) {

                                                    return (
                                                        <option key={key}>{item.Company}</option>
                                                    )
                                                }.bind(this)) : <div></div>}
                                            </select>
                                        </div>
                                        <div className="form-group col-md-2">
                                            <label>Vendor</label>
                                            <select className="form-control" id='vendor' onChange={e => { this.getUserByVendor(e.target.value) }}>
                                                <option>Choose Vendor</option>
                                                {this.state.allVendors ? this.state.allVendors.map(function (item, key) {
                                                    return (
                                                        <option key={key}>{item.Company}</option>
                                                    )
                                                }.bind(this)) : <div></div>}
                                            </select>
                                        </div>
                                        <div className="form-group col-md-2">
                                            <label>Vendor User</label>
                                            <select className="form-control" id='client' onChange={e => { this.setState({username:e.target.value})}}>
                                                <option>Choose User</option>
                                                {this.state.alluser ? this.state.alluser.map(function (item, key) {
                                                    return (
                                                        <option key={key}>{item.Username}</option>
                                                    )
                                                }.bind(this)) : <div></div>}
                                            </select>
                                        </div>
                                        
                                    </div>

                                </form>
                                <button id="submit" type="submit" name="submit" style={{ marginBottom: "10px" }} className="btn btn-primary  col-md-8" onClick={this.submitTask} value="submit">Submit</button>
                            </div>
                        </div>

                    </div>
                </div>
            </div>
        </div>);
    }

    protected getUserByVendor(vendor:string){
        this.setState({vendor:vendor})
        let name = vendor.replace(" ","%20")
        $.ajax({
            url: 'https://rpntechserver.appspot.com/findUsersByCompany?company='+name,
            method: 'GET',
            datatype: "json",
            headers: {
                Authorization: "Bearer " + localStorage.getItem('Token'),
            },
            
            success: function (data) {
                console.log(data);
                this.setState({alluser:data})

            }.bind(this),
        });
    }

    protected pushPage(page: String) {
        this.props.history.push(page)
    }

    protected submitTask() {
        let name = [];
        name.push(this.state.username);
        let StartDate = new Array(7);
        StartDate[0]=$('#startdate').val();
        let DueDate = new Array(7);
        DueDate[0]=$('#duedate').val();
        let citylist=$('#state').val()+"/"+$('#county').val()+"/"+$('#city').val()+"/"+$('#zipcode').val();
        let CompletionDate = new Array(7);
        

        $.ajax({
            url: 'https://rpntechserver.appspot.com/initTask',
            method: 'POST',
            datatype: "json",
            headers: {
                Authorization: "Bearer " + localStorage.getItem('Token'),
            },
            data: JSON.stringify({
                asset_num: $('#assetnum').val(),
                StartDate: StartDate,
                DueDate: DueDate,
                CompletionDate: CompletionDate,
                City: citylist,
                Address: $('#propaddr').val(),
                Desc: $('#description').val(),
                keycode: $('#lockboxnumber').val(),
                client: this.state.client,
                Username: name,
                Vendor: this.state.vendor
                //stage:$('#stage').val()
            }),
            success: function (data) {
                //console.log(data);
                this.props.history.push('/main');

            }.bind(this),
        });
    }
}

export default PageGhotiAddtask;
