/**
 * @author Tim
 * @overview generated by ghoti-cli
 * @fileoverview Page set PageGhotiDevelop
 */

import * as React from 'react';
import * as Component from '../component/import';
import * as Func from '../func/import';
import * as Lambda from '../lambda/import';
import * as XLSX from 'js-xlsx'
import * as $ from "jquery";

import Config from '../config/config';

export interface IProps {

}

export interface IState {

}

class PageGhotiDevelop extends React.Component<IProps, IState> {
    public constructor(props) {
        super(props);
    }

    public render() {
        return (<React.Fragment>
            <input onChange={e => this.uploadFile(e.target.files)} type="file"></input>
        </React.Fragment>);
    }

    protected uploadFile(file: FileList) {
        var f = file[0];

        var reader = new FileReader();
        var name = f.name;
        reader.onload = function (e:any) {
            var data = e.target.result;

            var workbook = XLSX.read(data, { type: 'binary' });
            var sheet = workbook.Sheets[workbook.SheetNames[0]];
            console.log(XLSX.utils.sheet_to_json(sheet));

            // console.log(workbook)
        };
        reader.readAsBinaryString(f);
    }
    

}

export default PageGhotiDevelop;
