/**
* @overview generated by ghoti-cli
* @fileoverview page import file
* You should not edit this file by hand
*/

import PageGhotiLogin from './login.page';
import PageGhotiMain from './main.page';
import PageGhotiEdittask from './edittask.page';
import PageGhotiUserProfile from './userProfile.page';
import PageGhotiRegister from './register.page';
import PageGhotiAddtask from './addtask.page';
import PageGhotiGeneralProfile from './generalProfile.page';
import PageGhotiPrintTask from './printTask.page';
import PageGhotiClientEdit from './clientEdit.page';
import PageGhotiVendorEdit from './vendorEdit.page';
import PageGhotiChecklist from './checklist.page';
import PageGhotiPrintText from './printText.page';
import PageGhotiPrintSub from './printSub.page';
import PageGhotiPrintSubText from './printSubText.page';
import PageGhotiDevelop from './develop.page';
export {
    PageGhotiLogin as login,
    PageGhotiMain as main,
    PageGhotiEdittask as edittask,
    PageGhotiUserProfile as userProfile,
    PageGhotiRegister as register,
    PageGhotiAddtask as addtask,
    PageGhotiGeneralProfile as generalProfile,
    PageGhotiPrintTask as printTask,
    PageGhotiClientEdit as clientEdit,
    PageGhotiVendorEdit as vendorEdit,
    PageGhotiChecklist as checklist,
    PageGhotiPrintText as printText,
    PageGhotiPrintSub as printSub,
    PageGhotiPrintSubText as printSubText,
    PageGhotiDevelop as develop,
};
