/**
* @overview generated by ghoti-cli
* @fileoverview page import file
* You should not edit this file by hand
*/

import PageGhotiLogin from './login.page';
import PageGhotiMain from './main.page';
import PageGhotiEdittask from './edittask.page';
import PageGhotiUserProfile from './userProfile.page';
import PageGhotiRegister from './register.page';
import PageGhotiAddtask from './addtask.page';
import PageGhotiGeneralProfile from './generalProfile.page';
export {
    PageGhotiLogin as login,
    PageGhotiMain as main,
    PageGhotiEdittask as edittask,
    PageGhotiUserProfile as userProfile,
    PageGhotiRegister as register,
    PageGhotiAddtask as addtask,
    PageGhotiGeneralProfile as generalProfile,
};
