/**
 * @author Tim
 * @overview generated by ghoti-cli
 * @fileoverview Page set PageGhotiLogin
 */

import * as React from 'react';
import * as Component from '../component/import';
import * as Func from '../func/import';
import * as Lambda from '../lambda/import';

import Config from '../config/config';

import * as $ from "jquery"


export interface IProps {
    history: any
}

export interface IState {

}

class PageGhotiLogin extends React.Component<IProps, IState> {
    public constructor(props) {
        super(props);
        this.login = this.login.bind(this)
    }

    public render() {
        return (
            <React.Fragment>
                <div className="login">
                    <section className="login-block">
                        <div className="containner">
                            <div className='row'>
                                <div className="col-md-4 login-sec">
                                    <h2 className="text-center">Login</h2>
                                    <form className="login-form">
                                        <div className="form-group">
                                            <label className="text-uppercase">Username</label>
                                            <input type="text" id="UN" className="form-control" placeholder="" />
                                        </div>
                                        <div className="form-group">
                                            <label className="text-uppercase">Password</label>
                                            <input type="password" id="PW" className="form-control" placeholder="" />

                                        </div>


                                        <button type="button" className="btn btn-login float-right" onClick={this.login}>LogIn</button>
                                        <div style={{
                                            width: "50%",
                                            visibility: "hidden",
                                            //height: "40px"
                                        }} className="alert alert-danger" role="alert" id="errormsg" >
                                            Wrong Username or Password
                                            </div>
                                    </form>
                                    <div style={{ marginLeft: "5%" }} className="copy-text"><div>© 2019 <a style={{ color: "blue" }} href="www.rpncompany.com">REPAIR AND PRESERVATION NETWORK LLC.</a></div></div>
                                </div>
                                <div className="col-md-8 banner-sec">


                                    <div id="carouselExampleIndicators" className="carousel slide" data-ride="carousel">

                                        <div className="carousel-inner" role="listbox">
                                            <div className="carousel-item active">
                                                <img className="d-block img-fluid" src="https://www.googleapis.com/download/storage/v1/b/post-images-rpntech/o/8b3309a8-7a15-4541-9a83-bed56bd6ea54?generation=1550684692370305&alt=media" alt="First slide" />
                                                <div className="carousel-caption d-none d-md-block">
                                                    <div style={{ marginBottom: "10%" }} className="banner-text">
                                                        <h2 style={{}}>Start From RPN</h2>
                                                        <p style={{}}>Our best-in-class services and reputation rely upon our core corporate values of quality, commitment and integrity. These values are thoroughly integrated in our day-to-day work with our clients, our vendor partners and our employees.</p>
                                                        <p style={{}}>Repair and Preservation Network is headquartered in White Plains, New York. Our other operation facilities are located in Des Moines, Iowa and Chicago, Illinois. We provide nationwide coverage of our services.</p>
                                                    </div>
                                                </div>
                                            </div>

                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </section>
                </div>
            </React.Fragment>
        );
    }
    protected login() {

        $.ajax({
            url: 'https://rpntechserver.appspot.com/login',
            method: 'POST',
            datatype: "json",
            data: JSON.stringify({
                username: $('#UN').val(),
                password: $('#PW').val(),
            }),
            success: (function (data) {
                // console.log(data);
                var result = JSON.parse(data);
                //this.IProps.key = data;
                //console.log(result.Authority);
                //console.log(result);
                localStorage.setItem('Token', result.Token);
                localStorage.setItem('Authority', result.Authority);
                localStorage.setItem('currUser', result.Username);
                localStorage.setItem('company', result.Company);
                this.props.history.push('/main');
            }).bind(this),
            error: (function (jqXHR, textStatus, errorThrown) {
                //console.log(msg);
                $("#errormsg").css('visibility', 'visible');

            }),
        });
    }
}

export default PageGhotiLogin;
