/**
 * @author Tim
 * @overview generated by ghoti-cli
 * @fileoverview Page set PageGhotiRegister
 */

import * as React from 'react';
import * as Component from '../component/import';
import * as Func from '../func/import';
import * as Lambda from '../lambda/import';
import * as $ from "jquery";

import Config from '../config/config';

export interface IProps {
    history: any
}

export interface IState {

}

class PageGhotiRegister extends React.Component<IProps, IState> {
    height: number = 0
    state = {
        Username: '',
        Name: '',
        Password: '',
        Authority: '',
        currStage: '0',
        checklist: [],
        clientIcon: "",
        vendorIcon: "",

    };

    public componentDidMount() {
        $.ajax({
            url: "https://rpnserver.appspot.com/findAllVendors",
            method: 'GET',
            success: (function (result) {
                console.log(result)
            }.bind(this))
        })
        // $.ajax({
        //     url: "https://api.census.gov/data/2017/acs/acs1?get=B00001_001E,NAME&for=county:*&in=state:56",
        //     method: 'GET',
        //     success: (function (result) {
        //         console.log(result);
        //     })
        // })
    }
    public constructor(props) {
        super(props);
        this.pushPage = this.pushPage.bind(this);
        this.submitTask = this.submitTask.bind(this);

        this.showTable = this.showTable.bind(this);
        this.initCategory = this.initCategory.bind(this);
        this.addCategory = this.addCategory.bind(this);
        this.mapCategory = this.mapCategory.bind(this);
    }

    public render() {

        this.height = window.innerHeight * 0.7
        return (<div className="page">
            <Component.leftBar page="register" pushPage={this.pushPage.bind(this)} />
            <Component.topBar page="register" pushPage={this.pushPage.bind(this)} />
            <div className="content" style={{ display: "fixed" }}>
                <div style={{
                    color: "#283747",
                    fontWeight: "bold",
                    fontSize: "22px",
                    marginLeft: "15px",
                    marginTop: "5px"
                }}>Register</div>
                <div className="mainTable">
                    <div className="card shadow mb-4">
                        <div className="card-header py-3">
                            <div className="controls col-md-2 " style={{
                                // marginTop: "15px",
                                // marginLeft: "15px",
                                // width: "20%",
                                // height:"10%",
                            }}>

                                <select className="form-control " id='client' onChange={e => { this.setState({ currStage: e.target.value }) }}>
                                    <option value="0">User</option>
                                    <option value="1">Client</option>
                                    <option value="2">Vendor</option>
                                </select>

                            </div>
                        </div>
                        <div style={{ height: this.height, overflow: "auto" }} className="card-body">
                            {this.showTable()}
                        </div>
                    </div>
                </div>


            </div>
        </div>);
    }

    protected showTable() {
        if (this.state.currStage === '0') {
            return (
                // <table id="user">
                //     <tr>Username <input className="text" id='username' ></input></tr>
                //     <tr>Password <input className="text" id='password'></input></tr>
                //     <tr>Authority <input className="text" id='authority'></input></tr>
                //     <tr>Firstname <input className="text" id='firstname' ></input></tr>
                //     <tr>LastName <input className="text" id='lastname' ></input></tr>
                //     <tr>Email <input className="text" id='email' ></input></tr>
                //     <tr>Phone <input className="text" id='phone' ></input></tr>
                //     <tr>Background <input className="text" id='background' ></input></tr>
                // </table>
                <React.Fragment>
                    <div id="signupbox" style={{ marginTop: "5px", float: "left", width: "47%", borderRight: "1px solid #E5E5E5" }} className="mainbox col-md-6 col-md-offset-3 col-sm-8 col-sm-offset-2">
                        <div className="panel panel-info">
                            <form style={{}} className="form-horizontal" method="post">
                                <div id="div_id_propertyaddress" className="form-group required">
                                    <label className="control-label col-md-4  requiredField"> Username<span className="asteriskField"></span> </label>
                                    <div className="controls col-md-10 ">
                                        <input className="input-md  textinput textInput form-control" id="username" name="username" placeholder="Username..." style={{ marginBottom: "5px" }} type="text" ></input>
                                    </div>
                                </div>
                                <div id="div_id_assetnumber" className="form-group required">
                                    <label className="control-label col-md-4  requiredField"> Password<span className="asteriskField"></span> </label>
                                    <div className="controls col-md-10 ">
                                        <input className="input-md  textinput textInput form-control" id="password" name="password" placeholder="Password..." style={{ marginBottom: "5px" }} type="text" ></input>
                                    </div>
                                </div>
                                <div id="div_id_client" className="form-group required">
                                    <label className="control-label col-md-4  requiredField">Authority<span className="asteriskField"></span> </label>
                                    <div className="controls col-md-10 ">
                                        <select className="form-control mb-2 mr-sm-2 mb-sm-0" id='authority'>
                                            <option value="0">Contractor</option>
                                            <option value="1">Analyst</option>
                                            <option value="2">Admin</option>
                                            <option value="3">Client</option>

                                        </select>
                                    </div>
                                </div>
                                <div id="div_id_city" className="form-group required">
                                    <label className="control-label col-md-4  requiredField"> Firstname<span className="asteriskField"></span> </label>
                                    <div className="controls col-md-10 ">
                                        <input className="input-md  textinput textInput form-control" id="firstname" name="firstname" placeholder="Firstname..." style={{ marginBottom: "5px" }} type="text" ></input>
                                    </div>
                                </div>
                                <div id="div_id_city" className="form-group required">
                                    <label className="control-label col-md-4  requiredField"> Lastname<span className="asteriskField"></span> </label>
                                    <div className="controls col-md-10 ">
                                        <input className="input-md  textinput textInput form-control" id="lastname" name="lastname" placeholder="Lastname..." style={{ marginBottom: "5px" }} type="text" ></input>
                                    </div>
                                </div>
                            </form>
                            <button id="submit" name="submit" style={{ marginLeft: "15px" }} className="btn btn-primary col-md-9" onClick={this.submitTask} >Submit</button>

                        </div>
                    </div>
                    <div id="signupbox" style={{ marginTop: "5px", width: "47%", float: "right" }} className="mainbox col-md-6 col-md-offset-3 col-sm-8 col-sm-offset-2">
                        <form style={{}} className="form-horizontal" method="post">
                            <div id="div_id_city" className="form-group required">
                                <label className="control-label col-md-4  requiredField"> Email<span className="asteriskField"></span> </label>
                                <div className="controls col-md-10 ">
                                    <input className="input-md  textinput textInput form-control" id="email" name="email" placeholder="Email..." style={{ marginBottom: "5px" }} type="text" ></input>
                                </div>
                            </div>
                            <div id="div_id_city" className="form-group required">
                                <label className="control-label col-md-4  requiredField"> Phone<span className="asteriskField"></span> </label>
                                <div className="controls col-md-10 ">
                                    <input className="input-md  textinput textInput form-control" id="phone" name="phone" placeholder="Phone..." style={{ marginBottom: "5px" }} type="text" ></input>
                                </div>
                            </div>
                            <div id="div_id_city" className="form-group required">
                                <label className="control-label col-md-4  requiredField"> ABCNumber<span className="asteriskField"></span> </label>
                                <div className="controls col-md-10 ">
                                    <input className="input-md textinput textInput form-control" id="background" name="background" placeholder="Background..." style={{ marginBottom: "5px" }} type="text" ></input>
                                </div>
                            </div>
                        </form >
                    </div>
                </React.Fragment>

            )
        }
        else if (this.state.currStage === '1') {
            return (
                <React.Fragment>

                    <div id="signupbox" style={{ marginTop: "5px", float: "left", width: "47%", borderRight: "1px solid #E5E5E5" }} className="mainbox col-md-6 col-md-offset-3 col-sm-8 col-sm-offset-2">
                        <div className="panel panel-info" >
                            <form className="form-horizontal" method="post" >
                                <div id="div_id_propertyaddress" className="form-group required">
                                    <label className="control-label col-md-4  requiredField"> Company<span className="asteriskField"></span> </label>
                                    <div className="controls col-md-10 ">
                                        <input className="input-md  textinput textInput form-control" id="company" name="company" placeholder="Company..." style={{ marginBottom: "5px" }} type="text" ></input>
                                    </div>
                                </div>
                                <div id="div_id_assetnumber" className="form-group required">
                                    <label className="control-label col-md-4  requiredField"> Address<span className="asteriskField"></span> </label>
                                    <div className="controls col-md-10 ">
                                        <input className="input-md  textinput textInput form-control" id="address" name="address" placeholder="Address..." style={{ marginBottom: "5px" }} type="text" ></input>
                                    </div>
                                </div>
                                <div id="div_id_assetnumber" className="form-group required">
                                    <label className="control-label col-md-8  requiredField"> Icon<span className="asteriskField"></span> </label>
                                    <div style={{
                                        width: "60%",
                                        marginLeft: "15px"
                                    }} className="input-group-prepend input-group-sm">
                                        <span className="input-group-text">{this.state.clientIcon ? <img style={{ width: "25px", height: "25px" }} src={this.state.clientIcon} /> : <div></div>}</span>
                                        <div className=" custom-file">
                                            <input type="file" className="custom-file-input" id="inputGroupFile01" aria-describedby="inputGroupFileAddon01"
                                                onChange={(e) => { this.addIcon(e.target.files) }}></input>
                                            <label className="custom-file-label" >Upload Icon</label>
                                        </div>
                                    </div>
                                </div>
                            </form>
                            <button id="submit" type="submit" name="submit" style={{ marginLeft: "15px" }} className="btn btn-primary  col-md-9" onClick={this.submitTask} value="submit">Submit</button>
                        </div>
                    </div>
                    <div id="signupbox" style={{ marginTop: "15px", float: "right" }} className="mainbox col-md-6 col-md-offset-3 col-sm-8 col-sm-offset-2">
                        <div id="div_id_city" className="form-group required">
                            <label className="control-label col-md-4  requiredField"> CheckList--><span className="asteriskField"></span> </label>
                            <div className="controls col-md-8 ">

                            </div>
                        </div>
                        <div className="panel panel-info" >
                            {this.state.checklist.map(this.mapCategory)}
                            <button style={{ marginTop: "10px" }} className="btn btn-primary  col-md-8" onClick={this.addCategory} >AddCategory</button>
                        </div>
                    </div>
                </React.Fragment>
            )
        }
        else {
            return (
                <React.Fragment>
                    <div id="signupbox" style={{ marginTop: "5px", float: "left", width: "47%", borderRight: "1px solid #E5E5E5" }} className="mainbox col-md-6 col-md-offset-3 col-sm-8 col-sm-offset-2">
                        <div className="panel panel-info" >
                            <form className="form-horizontal" method="post" >
                                <div id="div_id_propertyaddress" className="form-group required">
                                    <label className="control-label col-md-4  requiredField"> Company<span className="asteriskField"></span> </label>
                                    <div className="controls col-md-10 ">
                                        <input className="input-md  textinput textInput form-control" id="Vendor" name="Vendor" placeholder="Company..." style={{ marginBottom: "5px" }} type="text" ></input>
                                    </div>
                                </div>
                                <div id="div_id_assetnumber" className="form-group required">
                                    <label className="control-label col-md-4  requiredField"> Address<span className="asteriskField"></span> </label>
                                    <div className="controls col-md-10 ">
                                        <input className="input-md  textinput textInput form-control" id="VendorAddress" name="VendorAddress" placeholder="Address..." style={{ marginBottom: "5px" }} type="text" ></input>
                                    </div>
                                </div>
                                <div id="div_id_assetnumber" className="form-group required">
                                    <label className="control-label col-md-4  requiredField"> Primary Contact<span className="asteriskField"></span> </label>
                                    <div className="controls col-md-10 ">
                                        <input className="input-md  textinput textInput form-control" id="VendorUser" name="vendoraddress" placeholder="Contact..." style={{ marginBottom: "5px" }} type="text" ></input>
                                    </div>
                                </div>
                                <div id="div_id_assetnumber" className="form-group required">
                                    <label className="control-label col-md-4  requiredField"> Phone<span className="asteriskField"></span> </label>
                                    <div className="controls col-md-10 ">
                                        <input className="input-md  textinput textInput form-control" id="VendorPhone" name="VendorPhone" placeholder="Phone..." style={{ marginBottom: "5px" }} type="text" ></input>
                                    </div>
                                </div>
                                <div id="div_id_assetnumber" className="form-group required">
                                    <label className="control-label col-md-4  requiredField"> Email<span className="asteriskField"></span> </label>
                                    <div className="controls col-md-10">
                                        <input className="input-md  textinput textInput form-control" id="VendorEmail" name="VendorEmail" placeholder="Eamil..." style={{ marginBottom: "5px" }} type="text" ></input>
                                    </div>
                                </div>
                                <div id="div_id_assetnumber" className="form-group required">
                                    <label className="control-label col-md-4  requiredField"> EIN/SSN<span className="asteriskField"></span> </label>
                                    <div className="controls col-md-10 ">
                                        <input className="input-md  textinput textInput form-control" id="EINorSSN" name="EINorSSN" placeholder="EIN/SSN..." style={{ marginBottom: "5px" }} type="text" ></input>
                                    </div>
                                </div>
                                <div id="div_id_assetnumber" className="form-group required">
                                    <label className="control-label col-md-4  requiredField"> Insurance<span className="asteriskField"></span> </label>
                                    <div className="controls col-md-10 ">
                                        <input className="input-md  textinput textInput form-control" id="Insurance" name="Insurance" placeholder="Insurance..." style={{ marginBottom: "5px" }} type="text" ></input>
                                    </div>
                                </div>
                                <div id="div_id_assetnumber" className="form-group required">
                                    <label className="control-label col-md-6  requiredField"> Insurance Expire Date<span className="asteriskField"></span> </label>
                                    <div className="controls col-md-10 ">
                                        <input type="date" className="input-md  textinput textInput form-control" id="IEDate" name="IEDate" style={{ marginBottom: "5px" }}></input>
                                    </div>
                                </div>
                                <div id="div_id_assetnumber" className="form-group required">
                                    <label className="control-label col-md-4  requiredField"> ABCNumber<span className="asteriskField"></span> </label>
                                    <div className="controls col-md-10 ">
                                        <input className="input-md  textinput textInput form-control" id="ABCNumber" name="ABCNumber" placeholder="ABCNumber..." style={{ marginBottom: "5px" }} type="text" ></input>
                                    </div>
                                </div>
                                <div id="div_id_assetnumber" className="form-group required">
                                    <label className="control-label col-md-4  requiredField"> ICOLevel<span className="asteriskField"></span> </label>
                                    <div className="controls col-md-10 ">
                                        <input className="input-md  textinput textInput form-control" id="ICOLevel" name="ICOLevel" placeholder="ICOLevel..." style={{ marginBottom: "5px" }} type="text" ></input>
                                    </div>
                                </div>

                                <div id="div_id_assetnumber" className="form-group required">
                                    <label className="control-label col-md-4  requiredField"> Icon<span className="asteriskField"></span> </label>
                                    <div style={{
                                        width: "60%",
                                        marginLeft: "15px"
                                    }} className="input-group-prepend input-group-sm">
                                        <span className="input-group-text">{this.state.vendorIcon ? <img style={{ width: "25px", height: "25px" }} src={this.state.vendorIcon} /> : <div></div>}</span>
                                        <div className="custom-file">
                                            <input type="file" className="custom-file-input" id="inputGroupFile01" aria-describedby="inputGroupFileAddon01"
                                                onChange={(e) => { this.addIcon(e.target.files) }}></input>
                                            <label className="custom-file-label" >Upload Icon</label>
                                        </div>
                                    </div>
                                </div>
                            </form>
                            <button id="submit" type="submit" name="submit" style={{ marginLeft: "15px" }} className="btn btn-primary  col-md-9" onClick={this.submitTask} value="submit">Submit</button>
                        </div>
                    </div>
                    <div id="signupbox" style={{ marginTop: "15px", width: "47%", float: "right" }} className="mainbox col-md-6 col-md-offset-3 col-sm-8 col-sm-offset-2">
                        <div id="div_id_assetnumber" className="form-group required">
                            <label className="control-label col-md-4  requiredField"> Performed Services<span className="asteriskField"></span> </label>
                            <div style={{ marginLeft: "15px" }} className="form-check">
                                <input style={{ marginTop: "7px" }} className="form-check-input" type="checkbox" id="PropertyInspection" />
                                <label className="form-check-label">
                                    Property Inspection
                                        </label>
                            </div>
                            <div style={{ marginLeft: "15px" }} className="form-check">
                                <input style={{ marginTop: "7px" }} className="form-check-input" type="checkbox" id="PropertyPreservation" />
                                <label className="form-check-label">
                                    Property Preservation
                                        </label>
                            </div>
                            <div style={{ marginLeft: "15px" }} className="form-check">
                                <input style={{ marginTop: "7px" }} className="form-check-input" type="checkbox" id="REO" />
                                <label className="form-check-label">
                                    REO
                                        </label>
                            </div>
                            <div style={{ marginLeft: "15px" }} className="form-check">
                                <input style={{ marginTop: "7px" }} className="form-check-input" type="checkbox" id="HazardClaim" />
                                <label className="form-check-label">
                                    Hazard Claim
                                        </label>
                            </div>
                            <div style={{ marginLeft: "15px" }} className="form-check">
                                <input style={{ marginTop: "7px" }} className="form-check-input" type="checkbox" id="QualityControl" />
                                <label className="form-check-label">
                                    Quality Control
                                        </label>
                            </div>
                        </div>
                        <div id="div_id_assetnumber" className="form-group required">
                            <label className="control-label col-md-4  requiredField"> Licensed Services<span className="asteriskField"></span> </label>
                            <div style={{ marginLeft: "15px" }} className="form-check">
                                <input style={{ marginTop: "7px" }} className="form-check-input" type="checkbox" id="MoldRemediation" />
                                <label className="form-check-label">
                                    Mold Remediation
                                        </label>
                            </div>
                            <div style={{ marginLeft: "15px" }} className="form-check">
                                <input style={{ marginTop: "7px" }} className="form-check-input" type="checkbox" id="Electrical" />
                                <label className="form-check-label">
                                    Electrical
                                        </label>
                            </div>
                            <div style={{ marginLeft: "15px" }} className="form-check">
                                <input style={{ marginTop: "7px" }} className="form-check-input" type="checkbox" id="Demolition" />
                                <label className="form-check-label">
                                    Demolition
                                        </label>
                            </div>
                            <div style={{ marginLeft: "15px" }} className="form-check">
                                <input style={{ marginTop: "7px" }} className="form-check-input" type="checkbox" id="Plumbing" />
                                <label className="form-check-label">
                                    Plumbing
                                        </label>
                            </div>
                            <div style={{ marginLeft: "15px" }} className="form-check">
                                <input style={{ marginTop: "7px" }} className="form-check-input" type="checkbox" id="HealthHazard" />
                                <label className="form-check-label">
                                    Health Hazard
                                        </label>
                            </div>
                            <div style={{ marginLeft: "15px" }} className="form-check">
                                <input style={{ marginTop: "7px" }} className="form-check-input" type="checkbox" id="Roofing" />
                                <label className="form-check-label">
                                    Roofing
                                        </label>
                            </div>
                            <div style={{ marginLeft: "15px" }} className="form-check">
                                <input style={{ marginTop: "7px" }} className="form-check-input" type="checkbox" id="GeneralContracting" />
                                <label className="form-check-label">
                                    General Contracting
                                        </label>
                            </div>
                        </div>
                        <div id="div_id_assetnumber" className="form-group required">
                            <div className="form-group">
                                <label >Cover State (Format: State-County) (Use line break to separate State-County) </label>
                                <textarea id="CoverState" style={{ width: "70%", height: "150px" }}>

                                </textarea>
                            </div>
                        </div>
                    </div>
                </React.Fragment>
            )
        }
    }


    protected addIcon(File: FileList) {
        var formData = new FormData();
        formData.append('image', File[0]);
        $.ajax({
            url: 'https://rpntechserver.appspot.com/uploadImage',
            method: 'POST',
            enctype: 'multipart/form-data',
            dataType: 'json',
            fileElementId: 'file-input',
            cache: false,
            processData: false,
            contentType: false,
            headers: {
                Authorization: "Bearer " + localStorage.getItem('Token'),
            },
            data: formData,
            success: function (result) {
                if (this.state.currStage === "1") {
                    this.setState({ clientIcon: result });
                }
                else {
                    this.setState({ vendorIcon: result });
                }

            }.bind(this),
        });
    }

    protected addCategory() {
        let list = this.state.checklist;
        list.push(this.initCategory());
        this.setState({ checklist: list });
    }

    protected initCategory() {
        return {
            Category: "",
            Questions: [],
        }
    }



    protected mapCategory(item, key) {
        return (
            <React.Fragment key={key}>
                <button style={{ marginBottom: "10px" }} className="btn btn-primary  col-md-8" onClick={() => {
                    let list = this.state.checklist;
                    list.splice(key, 0, this.initCategory());
                    this.setState({ checklist: list });
                }} >AddCategory</button>
                <div className="card-header col-md-8">

                    <div className="input-group-prepend input-group-sm" style={{ marginBottom: "0px" }}>
                        <button style={{}} className="btn btn-danger center" onClick={() => {
                            let list = this.state.checklist;
                            list.splice(key, 1);
                            this.setState({ checklist: list });
                        }}></button>
                        <span className="input-group-text" id="basic-addon1" style={{
                            color: "black",
                            height: "31px"
                            // fontSize:'13px'
                        }}>Category</span>

                        <input type="text" className="form-control" placeholder="Category..." aria-label="Category" aria-describedby="basic-addon1"
                            id='cate' value={item.Category}
                            style={{
                                color: "black",
                                // width:"99%"
                            }}
                            onChange={e => {
                                let list = this.state.checklist;
                                list[key].Category = e.target.value;
                                this.setState({ checklist: list });
                            }}
                        ></input>
                    </div>
                    <div className="card-body">
                        {item.Questions.map(function (ques, index) {
                            return (
                                <React.Fragment key={index}>
                                    <button style={{ marginBottom: "10px" }} className="btn btn-info col-md-12 " onClick={() => {
                                        let list = this.state.checklist;
                                        list[key].Questions.splice(index, 0, "");
                                        // console.log(list[key].Questions);
                                        this.setState({ checklist: list });
                                    }} >AddQuestions</button>
                                    <div className="input-group-prepend input-group-sm" style={{ marginBottom: "0px" }}>
                                        <button style={{}} className="btn btn-danger center" onClick={() => {
                                            let list = this.state.checklist;
                                            list[key].Questions.splice(index, 1);
                                            this.setState({ checklist: list });
                                        }}></button>
                                        <span className="input-group-text" id="basic-addon1" style={{
                                            color: "black",
                                            height: "100px"
                                            // fontSize:'13px'
                                        }}>Question{index + 1}</span>
                                        <textarea className="form-control" placeholder="Question..." aria-label="DescriptionCN" aria-describedby="basic-addon1"
                                            id='descriptionCN' value={ques}
                                            onChange={e => {
                                                // console.log(this.state.checklist[key].Questions)
                                                let list = this.state.checklist;
                                                list[key].Questions[index] = e.target.value;
                                                this.setState({ checklist: list });
                                            }}
                                            style={{
                                                // width: "425px",
                                                height: "100px",
                                                resize: "none"
                                            }}>
                                            ></textarea>
                                    </div>
                                </React.Fragment>
                            )
                        }.bind(this))}
                        <div>
                            <button style={{ marginTop: "10px" }} className="btn btn-info col-md-12" onClick={() => {
                                let list = this.state.checklist;
                                list[key].Questions.push("");
                                this.setState({ checklist: list });
                            }} >AddQuestions</button>
                        </div>
                    </div>
                </div>
            </React.Fragment>
        )
    }
    protected pushPage(page: String) {
        this.props.history.push(page)
    }
    protected submitTask() {
        if (this.state.currStage === '0') {
            $.ajax({
                url: 'https://rpntechserver.appspot.com/register',
                //url: 'http://localhost:8080/login',
                method: 'POST',
                datatype: "json",
                headers: {
                    Authorization: "Bearer " + localStorage.getItem('Token'),
                },
                data: JSON.stringify({
                    username: $('#username').val(),
                    password: $('#password').val(),
                    authority: $('#authority').val(),
                    firstname: $('#firstname').val(),
                    lastname: $('#lastname').val(),
                    email: $('#email').val(),
                    phone: $('#phone').val(),
                    background: $('#background').val(),
                }),
                success: function (data) {
                    console.log(data);
                    this.props.history.push('/main');
                }.bind(this),
            });
        }
        else if (this.state.currStage === '1') {
            // console.log( $('#company').val(),
            // $('#address').val(),
            // $('#checklist').val(),);
            $.ajax({
                url: 'https://rpntechserver.appspot.com/createClient',
                //url: 'http://localhost:8080/login',
                method: 'POST',
                datatype: "json",
                headers: {
                    Authorization: "Bearer " + localStorage.getItem('Token'),
                },
                data: JSON.stringify({
                    company: $('#client').val(),
                    address: $('#clientaddress').val(),
                    check_list: this.state.checklist,
                    icon: this.state.clientIcon

                }),
                success: function (data) {
                    console.log(data);
                    this.props.history.push('/main');
                }.bind(this),
            });
        }
        else {
            let PerformedServices = [];
            $('#PropertyInspection').prop("checked") ? PerformedServices.push("PropertyInspection") : void 0
            $('#PropertyPreservation').prop("checked") ? PerformedServices.push("PropertyPreservation") : void 0
            $('#REO').prop("checked") ? PerformedServices.push("REO") : void 0
            $('#HazardClaim').prop("checked") ? PerformedServices.push("HazardClaim") : void 0
            $('#QualityControl').prop("checked") ? PerformedServices.push("QualityControl") : void 0

            let LicensedServices = [];
            $('#MoldRemediation').prop("checked") ? LicensedServices.push("MoldRemediation") : void 0
            $('#Electrical').prop("checked") ? LicensedServices.push("Electrical") : void 0
            $('#Demolition').prop("checked") ? LicensedServices.push("Demolition") : void 0
            $('#Plumbing').prop("checked") ? LicensedServices.push("Plumbing") : void 0
            $('#HealthHazard').prop("checked") ? LicensedServices.push("HealthHazard") : void 0
            $('#Roofing').prop("checked") ? LicensedServices.push("Roofing") : void 0
            $('#GeneralContracting').prop("checked") ? LicensedServices.push("GeneralContracting") : void 0
            let CoverState = $('#CoverState').val();
            CoverState = CoverState.split("\n")
            // console.log(CoverState);
            let StateCounty = [];
            for (let i = 0; i < CoverState.length; i++) {
                if (CoverState[i]) {
                    let State = CoverState[i].split("-")[0];
                    let County = CoverState[i].split("-")[1];
                    State = State.replace(" ", "")
                    County = County.replace(" ","_")
                    StateCounty.push({ state: State, county: County })
                }
            }
            console.log(StateCounty);
            // console.log($('#CoverState').val())

            // console.log($('#Vendor').val())
            // console.log($('#VendorAddress').val())
            // console.log($('#VendorUser').val())
            // console.log($('#VendorPhone').val())
            // console.log($('#VendorEmail').val())
            // console.log($('#EINorSSN').val())
            // console.log($('#Insurance').val())
            // console.log($('#IEDate').val())
            // console.log($('#ABCNumber').val())
            // console.log($('#ICOLevel').val())
            // console.log($('#PropertyInspection').prop("checked"))
        }
    }
}

export default PageGhotiRegister;
