/**
 * @author Tim
 * @overview generated by ghoti-cli
 * @fileoverview Page set PageGhotiUserProfile
 */

import * as React from 'react';
import * as Component from '../component/import';
import * as Func from '../func/import';
import * as Lambda from '../lambda/import';

import Config from '../config/config';

export interface IProps {
    history: any
}

export interface IState {

}

class PageGhotiUserProfile extends React.Component<IProps, IState> {
    public constructor(props) {
        super(props);
        this.pushPage = this.pushPage.bind(this)
    }

    public render() {
        return (<div className="page">
            <Component.leftBar page="userProfile" pushPage={this.pushPage.bind(this)}/>
            <Component.topBar page="userProfile" pushPage={this.pushPage.bind(this)}/>
            <div>userProfile</div>
        </div>);
    }
    protected pushPage(page:String){
        this.props.history.push(page)
    }
}

export default PageGhotiUserProfile;
