let InitialService = [
    {
        After: [],
        Amount: 0,
        Before: [],
        During: [],
        Process: '0',
        Status: '0',
        Tax: 0,
        Taxable: true,
        description: 'Re-key secondary doors (excluding boarded, sliding glass, and door with lockbox). May not have',
        Cate: 'InitialService',
        Comments: '',
        Item: 1,
        Qty: 0,
        UM: '',
        PPU: 0,
        Cost: 0,
        SubCost: 0,
        SubPPU: 0,
        Pano: "",
        description_cn: "除了挂钥匙盒的门锁，换其余室外门的锁（包括室外小仓房）, 拍钥匙盒带密码和钥匙盒内照片（不同角度多拍几组）",
        measure: "",
        completeness: "0"
    },
    {
        After: [],
        Amount: 0,
        Before: [],
        During: [],
        Process: '0',
        Status: '0',
        Tax: 0,
        Taxable: true,
        description: 'Shrub trimming (Keep shrub 6 inch away from property) May not have',
        Cate: 'InitialService',
        Comments: '',
        Item: 2,
        Qty: 0,
        UM: '',
        PPU: 0,
        Cost: 0,
        SubCost: 0,
        SubPPU: 0,
        Pano: "",
        description_cn: "房子周围灌木丛，草丛修剪（如果离房子小于6英寸，修剪到离房子至少1尺）",
        measure: "",
        completeness: "0"
    },
    {
        After: [],
        Amount: 0,
        Before: [],
        During: [],
        Process: '0',
        Status: '0',
        Tax: 0,
        Taxable: true,
        description: 'Roof damages? If roof is leaking, tarp the roof. ',
        Cate: 'InitialService',
        Comments: '',
        Item: 3,
        Qty: 0,
        UM: '',
        PPU: 0,
        Cost: 0,
        SubCost: 0,
        SubPPU: 0,
        Pano: "",
        description_cn: "房顶是否有漏水？如果有，铺防雨布",
        measure: "",
        completeness: "0"
    },
    {
        After: [],
        Amount: 0,
        Before: [],
        During: [],
        Process: '0',
        Status: '0',
        Tax: 0,
        Taxable: true,
        description: 'Snow and ice removal (Walkway and driveway) May not have',
        Cate: 'InitialService',
        Comments: '',
        Item: 4,
        Qty: 0,
        UM: '',
        PPU: 0,
        Cost: 0,
        SubCost: 0,
        SubPPU: 0,
        Pano: "",
        description_cn: "除雪（车道和人行道）",
        measure: "",
        completeness: "0"
    },
    {
        After: [],
        Amount: 0,
        Before: [],
        During: [],
        Process: '0',
        Status: '0',
        Tax: 0,
        Taxable: true,
        description: 'Vehicle Removal. May not have',
        Cate: 'InitialService',
        Comments: '',
        Item: 5,
        Qty: 0,
        UM: '',
        PPU: 0,
        Cost: 0,
        SubCost: 0,
        SubPPU: 0,
        Pano: "",
        description_cn: "如果有车，联系办公室",
        measure: "",
        completeness: "0"
    },
    {
        After: [],
        Amount: 0,
        Before: [],
        During: [],
        Process: '0',
        Status: '0',
        Tax: 0,
        Taxable: true,
        description: 'Graffiti removal. May not have',
        Cate: 'InitialService',
        Comments: '',
        Item: 6,
        Qty: 0,
        UM: '',
        PPU: 0,
        Cost: 0,
        SubCost: 0,
        SubPPU: 0,
        Pano: "",
        description_cn: "如果有涂鸦，清除涂鸦",
        measure: "",
        completeness: "0"
    },
    {
        After: [],
        Amount: 0,
        Before: [],
        During: [],
        Process: '0',
        Status: '0',
        Tax: 0,
        Taxable: true,
        description: ' Interior and exterior debris removal. Please estimate how many cubic yard',
        Cate: 'InitialService',
        Comments: '',
        Item: 7,
        Qty: 0,
        UM: '',
        PPU: 0,
        Cost: 0,
        SubCost: 0,
        SubPPU: 0,
        Pano: "",
        description_cn: "移除垃圾，按要求拍照并做好记录",
        measure: "",
        completeness: "0"
    },
    {
        After: [],
        Amount: 0,
        Before: [],
        During: [],
        Process: '0',
        Status: '0',
        Tax: 0,
        Taxable: true,
        description: 'Check basement sump pump. If it is not working, replace/repair one. May not to do',
        Cate: 'InitialService',
        Comments: '',
        Item: 8,
        Qty: 0,
        UM: '',
        PPU: 0,
        Cost: 0,
        SubCost: 0,
        SubPPU: 0,
        Pano: "",
        description_cn: "如果有地下室，拍照并记录是否有抽水泵",
        measure: "",
        completeness: "0"
    },
    {
        After: [],
        Amount: 0,
        Before: [],
        During: [],
        Process: '0',
        Status: '0',
        Tax: 0,
        Taxable: true,
        description: 'Install/replace smoke detectors. Make sure at least 1 in each room. May not to do',
        Cate: 'InitialService',
        Comments: '',
        Item: 9,
        Qty: 0,
        UM: '',
        PPU: 0,
        Cost: 0,
        SubCost: 0,
        SubPPU: 0,
        Pano: "",
        description_cn: "如果缺烟雾报警器，安装",
        measure: "",
        completeness: "0"
    },
    {
        After: [],
        Amount: 0,
        Before: [],
        During: [],
        Process: '0',
        Status: '0',
        Tax: 0,
        Taxable: true,
        description: 'Sales Clean (all flooring, surface)',
        Cate: 'InitialService',
        Comments: '',
        Item: 10,
        Qty: 0,
        UM: '',
        PPU: 0,
        Cost: 0,
        SubCost: 0,
        SubPPU: 0,
        Pano: "",
        description_cn: "室内清洁（扫地，拖地，擦窗台，擦所有台面，清洁马桶，浴池，哪儿脏清洁哪儿）",
        measure: "",
        completeness: "0"
    },
    {
        After: [],
        Amount: 0,
        Before: [],
        During: [],
        Process: '0',
        Status: '0',
        Tax: 0,
        Taxable: true,
        description: 'Boarding unsecured openings. May not to do',
        Cate: 'InitialService',
        Comments: '',
        Item: 11,
        Qty: 0,
        UM: '',
        PPU: 0,
        Cost: 0,
        SubCost: 0,
        SubPPU: 0,
        Pano: "",
        description_cn: "破窗户，房檐等需要钉木板，联系办公室",
        measure: "",
        completeness: "0"
    },
    {
        After: [],
        Amount: 0,
        Before: [],
        During: [],
        Process: '0',
        Status: '0',
        Tax: 0,
        Taxable: true,
        description: 'Replace missing/damaged outlet/switch cover plates. May not to do',
        Cate: 'InitialService',
        Comments: '',
        Item: 12,
        Qty: 0,
        UM: '',
        PPU: 0,
        Cost: 0,
        SubCost: 0,
        SubPPU: 0,
        Pano: "",
        description_cn: "暴露电线加盖，损坏或缺失面板更换",
        measure: "",
        completeness: "0"
    },
    {
        After: [],
        Amount: 0,
        Before: [],
        During: [],
        Process: '0',
        Status: '0',
        Tax: 0,
        Taxable: true,
        description: 'Exterior and interior photos after work.',
        Cate: 'InitialService',
        Comments: '',
        Item: 13,
        Qty: 0,
        UM: '',
        PPU: 0,
        Cost: 0,
        SubCost: 0,
        SubPPU: 0,
        Pano: "",
        description_cn: "室内外全景照片， 如果有游泳池，报告办公室， 检查水路是否有漏， 打开水龙头照片，其他任何破损或缺失",
        measure: "",
        completeness: "0"
    },
]

let BiWeekly = [
    {
        After: [],
        Amount: 0,
        Before: [],
        During: [],
        Process: '0',
        Status: '0',
        Tax: 0,
        Taxable: true,
        description: 'Lock box photo (With code and inside, take several with different angle)',
        Cate: 'BiWeekly',
        Comments: '',
        Item: 1,
        Qty: 0,
        UM: '',
        PPU: 0,
        Cost: 0,
        SubCost: 0,
        SubPPU: 0,
        Pano: "",
        description_cn: "钥匙盒照片",
        measure: "",
        completeness: "0"
    },
    {
        After: [],
        Amount: 0,
        Before: [],
        During: [],
        Process: '0',
        Status: '0',
        Tax: 0,
        Taxable: true,
        description: 'Interior and Exterior Photo',
        Cate: 'BiWeekly',
        Comments: '',
        Item: 2,
        Qty: 0,
        UM: '',
        PPU: 0,
        Cost: 0,
        SubCost: 0,
        SubPPU: 0,
        Pano: "",
        description_cn: "室外和室内照片",
        measure: "",
        completeness: "0"
    },
    {
        After: [],
        Amount: 0,
        Before: [],
        During: [],
        Process: '0',
        Status: '0',
        Tax: 0,
        Taxable: true,
        description: 'Kitchen faucet in opening position (Take several photos from different angle)',
        Cate: 'BiWeekly',
        Comments: '',
        Item: 3,
        Qty: 0,
        UM: '',
        PPU: 0,
        Cost: 0,
        SubCost: 0,
        SubPPU: 0,
        Pano: "",
        description_cn: "打开的厨房水龙头照片",
        measure: "",
        completeness: "0"
    },
    {
        After: [],
        Amount: 0,
        Before: [],
        During: [],
        Process: '0',
        Status: '0',
        Tax: 0,
        Taxable: true,
        description: 'Sales clean if needed',
        Cate: 'BiWeekly',
        Comments: '',
        Item: 4,
        Qty: 0,
        UM: '',
        PPU: 0,
        Cost: 0,
        SubCost: 0,
        SubPPU: 0,
        Pano: "",
        description_cn: "室内清洁，如果室内脏乱",
        measure: "",
        completeness: "0"
    },
    {
        After: [],
        Amount: 0,
        Before: [],
        During: [],
        Process: '0',
        Status: '0',
        Tax: 0,
        Taxable: true,
        description: 'Lawn mowing/snow plowing if needed',
        Cate: 'BiWeekly',
        Comments: '',
        Item: 5,
        Qty: 0,
        UM: '',
        PPU: 0,
        Cost: 0,
        SubCost: 0,
        SubPPU: 0,
        Pano: "",
        description_cn: "除草（超过12英寸）或除雪，如果需要",
        measure: "",
        completeness: "0"
    },
    {
        After: [],
        Amount: 0,
        Before: [],
        During: [],
        Process: '0',
        Status: '0',
        Tax: 0,
        Taxable: true,
        description: 'Tree/shrub trimming if needed (At least 1 ft away from property)',
        Cate: 'BiWeekly',
        Comments: '',
        Item: 6,
        Qty: 0,
        UM: '',
        PPU: 0,
        Cost: 0,
        SubCost: 0,
        SubPPU: 0,
        Pano: "",
        description_cn: "修剪树或灌木（离房子小于12英寸）",
        measure: "",
        completeness: "0"
    },
    {
        After: [],
        Amount: 0,
        Before: [],
        During: [],
        Process: '0',
        Status: '0',
        Tax: 0,
        Taxable: true,
        description: 'Cap any exposed wire',
        Cate: 'BiWeekly',
        Comments: '',
        Item: 7,
        Qty: 0,
        UM: '',
        PPU: 0,
        Cost: 0,
        SubCost: 0,
        SubPPU: 0,
        Pano: "",
        description_cn: "暴露电线加盖",
        measure: "",
        completeness: "0"
    },
    {
        After: [],
        Amount: 0,
        Before: [],
        During: [],
        Process: '0',
        Status: '0',
        Tax: 0,
        Taxable: true,
        description: 'Post "Warning" sign for the area missing handrail or has holes on floor',
        Cate: 'BiWeekly',
        Comments: '',
        Item: 8,
        Qty: 0,
        UM: '',
        PPU: 0,
        Cost: 0,
        SubCost: 0,
        SubPPU: 0,
        Pano: "",
        description_cn: "地板有洞或台阶缺少扶手的地方贴上“warning”的标志",
        measure: "",
        completeness: "0"
    },
    {
        After: [],
        Amount: 0,
        Before: [],
        During: [],
        Process: '0',
        Status: '0',
        Tax: 0,
        Taxable: true,
        description: 'If roof is leaking, tarp the roof',
        Cate: 'BiWeekly',
        Comments: '',
        Item: 9,
        Qty: 0,
        UM: '',
        PPU: 0,
        Cost: 0,
        SubCost: 0,
        SubPPU: 0,
        Pano: "",
        description_cn: "如果房顶有漏水，铺防雨布",
        measure: "",
        completeness: "0"
    },
    {
        After: [],
        Amount: 0,
        Before: [],
        During: [],
        Process: '0',
        Status: '0',
        Tax: 0,
        Taxable: true,
        description: 'Other issues/damages/hazard found',
        Cate: 'BiWeekly',
        Comments: '',
        Item: 10,
        Qty: 0,
        UM: '',
        PPU: 0,
        Cost: 0,
        SubCost: 0,
        SubPPU: 0,
        Pano: "",
        description_cn: "其他隐患或破损",
        measure: "",
        completeness: "0"
    },
]

let Winterization=[
    {
        After: [],
        Amount: 0,
        Before: [],
        During: [],
        Process: '0',
        Status: '0',
        Tax: 0,
        Taxable: true,
        description: 'pressure test, photo needs to show the gauge reading',
        Cate: 'Winterization',
        Comments: '',
        Item: 1,
        Qty: 0,
        UM: '',
        PPU: 0,
        Cost: 0,
        SubCost: 0,
        SubPPU: 0,
        Pano: "",
        description_cn: "压力表照片",
        measure: "",
        completeness: "0"
    },
    {
        After: [],
        Amount: 0,
        Before: [],
        During: [],
        Process: '0',
        Status: '0',
        Tax: 0,
        Taxable: true,
        description: 'Photos to show water has been shut off at meter/or main water "shut off" valve from inside.',
        Cate: 'Winterization',
        Comments: '',
        Item: 2,
        Qty: 0,
        UM: '',
        PPU: 0,
        Cost: 0,
        SubCost: 0,
        SubPPU: 0,
        Pano: "",
        description_cn: "从总闸关水",
        measure: "",
        completeness: "0"
    },
    {
        After: [],
        Amount: 0,
        Before: [],
        During: [],
        Process: '0',
        Status: '0',
        Tax: 0,
        Taxable: true,
        description: 'Photos to show drain HWH',
        Cate: 'Winterization',
        Comments: '',
        Item: 3,
        Qty: 0,
        UM: '',
        PPU: 0,
        Cost: 0,
        SubCost: 0,
        SubPPU: 0,
        Pano: "",
        description_cn: "热水器的水要放掉",
        measure: "",
        completeness: "0"
    },
    {
        After: [],
        Amount: 0,
        Before: [],
        During: [],
        Process: '0',
        Status: '0',
        Tax: 0,
        Taxable: true,
        description: 'If property has a wet heating system (boiler), drain all domestic lines',
        Cate: 'Winterization',
        Comments: '',
        Item: 4,
        Qty: 0,
        UM: '',
        PPU: 0,
        Cost: 0,
        SubCost: 0,
        SubPPU: 0,
        Pano: "",
        description_cn: "确定室内加热装置，如果是老式烧水暖气，放水",
        measure: "",
        completeness: "0"
    },
    {
        After: [],
        Amount: 0,
        Before: [],
        During: [],
        Process: '0',
        Status: '0',
        Tax: 0,
        Taxable: true,
        description: 'Are there any current plumbing damages?',
        Cate: 'Winterization',
        Comments: '',
        Item: 5,
        Qty: 0,
        UM: '',
        PPU: 0,
        Cost: 0,
        SubCost: 0,
        SubPPU: 0,
        Pano: "",
        description_cn: "检查室内所有管道是否有漏水",
        measure: "",
        completeness: "0"
    },
    {
        After: [],
        Amount: 0,
        Before: [],
        During: [],
        Process: '0',
        Status: '0',
        Tax: 0,
        Taxable: true,
        description: 'Shut off gas or electricity to the water heater',
        Cate: 'Winterization',
        Comments: '',
        Item: 6,
        Qty: 0,
        UM: '',
        PPU: 0,
        Cost: 0,
        SubCost: 0,
        SubPPU: 0,
        Pano: "",
        description_cn: "热水器电闸或气阀门必须关闭 ",
        measure: "",
        completeness: "0"
    },
    {
        After: [],
        Amount: 0,
        Before: [],
        During: [],
        Process: '0',
        Status: '0',
        Tax: 0,
        Taxable: true,
        description: 'Open all faucets to remove remaining water in lines. Add environmentally friendly colored antifreeze to all sinks, toilets, and bath tubs/showers',
        Cate: 'Winterization',
        Comments: '',
        Item: 7,
        Qty: 0,
        UM: '',
        PPU: 0,
        Cost: 0,
        SubCost: 0,
        SubPPU: 0,
        Pano: "",
        description_cn: "清洗所有马桶，水槽，打开水龙头方干管道内的水，并倒防冻液",
        measure: "",
        completeness: "0"
    },
    {
        After: [],
        Amount: 0,
        Before: [],
        During: [],
        Process: '0',
        Status: '0',
        Tax: 0,
        Taxable: true,
        description: 'Winterization signage posted on all sinks, toilets, and water heater',
        Cate: 'Winterization',
        Comments: '',
        Item: 8,
        Qty: 0,
        UM: '',
        PPU: 0,
        Cost: 0,
        SubCost: 0,
        SubPPU: 0,
        Pano: "",
        description_cn: "贴上rpn防冻标识，用胶带封住",
        measure: "",
        completeness: "0"
    },
    {
        After: [],
        Amount: 0,
        Before: [],
        During: [],
        Process: '0',
        Status: '0',
        Tax: 0,
        Taxable: true,
        description: 'Drain toilet tanks and take photos',
        Cate: 'Winterization',
        Comments: '',
        Item: 9,
        Qty: 0,
        UM: '',
        PPU: 0,
        Cost: 0,
        SubCost: 0,
        SubPPU: 0,
        Pano: "",
        description_cn: "马桶水缸照片",
        measure: "",
        completeness: "0"
    },
    {
        After: [],
        Amount: 0,
        Before: [],
        During: [],
        Process: '0',
        Status: '0',
        Tax: 0,
        Taxable: true,
        description: 'pressure test, photo needs to show the gauge reading',
        Cate: 'Winterization',
        Comments: '',
        Item: 10,
        Qty: 0,
        UM: '',
        PPU: 0,
        Cost: 0,
        SubCost: 0,
        SubPPU: 0,
        Pano: "",
        description_cn: "压力表照片",
        measure: "",
        completeness: "0"
    },
    {
        After: [],
        Amount: 0,
        Before: [],
        During: [],
        Process: '0',
        Status: '0',
        Tax: 0,
        Taxable: true,
        description: 'Clear plumbing system using compressor',
        Cate: 'Winterization',
        Comments: '',
        Item: 11,
        Qty: 0,
        UM: '',
        PPU: 0,
        Cost: 0,
        SubCost: 0,
        SubPPU: 0,
        Pano: "",
        description_cn: "用泵把水管里的水清除干净",
        measure: "",
        completeness: "0"
    },
]

export {
    InitialService,
    BiWeekly,
    Winterization
}