/**
 * @overview generated by ghoti-cli
 * @fileoverview Router
 */

import * as React from 'react';
import * as Component from './component/import';
import * as Func from './func/import';
import * as Lambda from './lambda/import';
import * as Page from './page/import';

import { Route } from 'react-router-dom';
import Config from './config/config';

class Hello extends React.Component<{}, {}> {
    public constructor(props) {
        super(props);
    }

    public render() {
        return (
            <React.Fragment>
                <Route path="/hello" component={() => {
                    return <div>Route</div>;
                }} />
                <Route path="/" exact component={Page.login} />
                <Route path="/main" component={Page.main} />
                <Route path="/edittask" component={Page.edittask} />
                <Route path="/userProfile" component={Page.userProfile} />
                <Route path="/generalProfile" component={Page.generalProfile} />
                <Route path="/register" component={Page.register} />
                <Route path="/addtask" component={Page.addtask} />
                <Route path="/printTask" component={Page.printTask} />
                <Route path="/printText" component={Page.printText} />
                <Route path="/checklist" component={Page.checklist} />
                <Route path="/clientEdit" component={Page.clientEdit} />
                <Route path="/vendorEdit" component={Page.vendorEdit} />
                <Route path="/photo" component={(props)=><div>{console.log(props)}{props.match.params.name}</div>}/>
            </React.Fragment>
        );
    }
}

export default Hello;
